apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scc-modifier
rules:
- apiGroups: ["security.openshift.io"]
  resources: ["securitycontextconstraints"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scc-modifier-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scc-modifier
subjects:
- kind: ServiceAccount
  name: rsct-operator-controller-manager
  namespace: rsct-operator-system
